// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import { group } from "k6";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    BASE_URL: "https://test-api.k6.io"
  },
  environment: {
    USERNAME: "test@example.com",
    PASSWORD: "superCroc2020",
    FIRSTNAME: "John",
    LASTNAME: "Doe",
    EMAIL: "test@example.com",
    ACCESS: null,
    REFRESH: null,
    CROCID: null
  }
});

export default function() {
  group("Public APIs", function() {
    postman[Request]({
      name: "List all public crocodiles",
      id: "b4843396-ee46-4c09-b705-ef7f91b20cdd",
      method: "GET",
      address: "{{BASE_URL}}/public/crocodiles/"
    });

    postman[Request]({
      name: "Get a single public crocodile",
      id: "3efa9c3a-dd78-490f-a7b8-6d58d29e51a2",
      method: "GET",
      address: "{{BASE_URL}}/public/crocodiles/1/"
    });
  });

  group("Registration and authentication", function() {
    postman[Request]({
      name: "Register a new user",
      id: "002e8d72-7efd-4b74-a822-6bc0972cb325",
      method: "POST",
      address: "{{BASE_URL}}/user/register/",
      data:
        '{\n    "username": "{{USERNAME}}",\n    "first_name": "{{FIRSTNAME}}",\n    "last_name": "{{LASTNAME}}",\n    "email": "{{EMAIL}}",\n    "password": "{{PASSWORD}}"\n}'
    });

    postman[Request]({
      name: "Bearer/JWT token authentication",
      id: "2d1f62e6-9ae5-4895-b637-e564adc0ff7c",
      method: "POST",
      address: "{{BASE_URL}}/auth/token/login/",
      data:
        '{\n    "username": "{{USERNAME}}",\n    "password": "{{PASSWORD}}"\n}',
      post(response) {
        var jsonData = JSON.parse(responseBody);
        pm.environment.set("REFRESH", jsonData.refresh);
        pm.environment.set("ACCESS", jsonData.access);
      }
    });
  });
}
